services:
  - type: web
    name: telegram-trading-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 bot.py
    plan: free
    region: frankfurt
    branch: main
    autoDeploy: true
